# Generated by Django 4.0.3 on 2022-05-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='left_on_stock',
            field=models.IntegerField(default=0),
        ),
    ]
