# Generated by Django 4.0.3 on 2022-05-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_left_on_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
